name: GHA-frac-Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3   
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev libgmock-dev cmake build-essential
    
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error" ..  # -Werror -> -Wno-error
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Run Tests
      run: |
        cd build
        if [ -f "test/ST-3.test" ]; then
          ./test/ST-3.test
        else
          echo "Test executable not found!"
          exit 1
        fi